#!/usr/bin/env python3
"""Regenerate the "Cost above baseline" table in README.md.

Reads the per-state figures in measurements/<State>.csv and the state metadata in
measurements/tags.tsv, and rewrites the block between the COST-TABLE markers in
README.md. The Baseline row is the frozen baseline; every later state is shown as
a byte delta above it. Run from anywhere:

    python3 scripts/gen-cost-table.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
MEAS = ROOT / "measurements"
README = ROOT / "README.md"

RAW_KEYS = ["flash_text", "flash_data", "static_bss", "heap_used", "stack_log", "stack_service"]

BASE_STATE = "Baseline"

# Derived, marketing-facing columns from the raw self-measured keys.
#   Flash      = read-only image (.text + .rodata) + .data init image
#   Static RAM = .data (copied to RAM) + .bss
DERIVED = [
    ("Flash", lambda d: d["flash_text"] + d["flash_data"]),
    ("Static RAM", lambda d: d["flash_data"] + d["static_bss"]),
    ("Heap", lambda d: d["heap_used"]),
    ("Log stack", lambda d: d["stack_log"]),
    ("Service stack", lambda d: d["stack_service"]),
]


def load_csv(state):
    values = {}
    for line in (MEAS / f"{state}.csv").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition(",")
        if key in RAW_KEYS:
            values[key] = int(value)
    missing = [k for k in RAW_KEYS if k not in values]
    if missing:
        raise SystemExit(f"{state}.csv missing keys: {missing}")
    return values


def load_states():
    rows = []
    for line in (MEAS / "tags.tsv").read_text(encoding="utf-8").splitlines():
        line = line.rstrip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 2:
            raise SystemExit(f"tags.tsv row must be state<TAB>what-it-adds: {line!r}")
        rows.append(parts)
    return rows


def main():
    # A state gets its tags.tsv row when its work starts and its CSV only when the
    # figures are frozen, so the two are briefly out of step. Show what is frozen
    # and say what was skipped, rather than failing or publishing a blank row.
    #
    # The baseline is named, not inferred from position: every figure in the table
    # is a delta above it, so the wrong reference is wrong silently.
    states = load_states()
    if not any(state == BASE_STATE for state, _ in states):
        raise SystemExit(f"measurements/tags.tsv has no {BASE_STATE} row")
    if not (MEAS / f"{BASE_STATE}.csv").exists():
        raise SystemExit(f"measurements/{BASE_STATE}.csv is required: every figure is a delta above it")

    pending = [state for state, _ in states if state != BASE_STATE and not (MEAS / f"{state}.csv").exists()]
    states = [row for row in states if row[0] not in pending]

    base = {name: fn(load_csv(BASE_STATE)) for name, fn in DERIVED}

    header = ["State", "What it adds"] + [name for name, _ in DERIVED]
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]

    for state, what in states:
        cur = load_csv(state)
        cells = [state, what]
        if state == BASE_STATE:
            cells += ["baseline" for _ in DERIVED]
        else:
            cells += [f"{fn(cur) - base[name]:+,}" for name, fn in DERIVED]
        lines.append("| " + " | ".join(cells) + " |")

    table = "\n".join(lines)
    base_note = "*Baseline: " + ", ".join(f"{name} {base[name]:,} B" for name, _ in DERIVED) + ".*"

    block = (
        "<!-- COST-TABLE:START (generated by scripts/gen-cost-table.py — do not edit by hand) -->\n\n"
        f"{table}\n\n{base_note}\n\n"
        "<!-- COST-TABLE:END -->"
    )

    text = README.read_text(encoding="utf-8")
    new_text, n = re.subn(r"<!-- COST-TABLE:START.*?COST-TABLE:END -->", block, text, count=1, flags=re.S)
    if n != 1:
        raise SystemExit("COST-TABLE markers not found in README.md")
    README.write_text(new_text, encoding="utf-8", newline="\n")
    print(f"updated README cost table ({len(states)} state(s))")
    if pending:
        print(f"not yet frozen, so left out: {', '.join(pending)}")


if __name__ == "__main__":
    main()
