#!/usr/bin/env python3
"""Regenerate the "Cost above baseline" table in README.md.

Reads the per-state figures in measurements/<State>.csv and the state metadata in
measurements/tags.tsv, and rewrites the block between the COST-TABLE markers in
README.md. The first row (Baseline) is the frozen baseline; every later state is
shown as a byte delta above it. Run from anywhere:

    python3 scripts/gen-cost-table.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
MEAS = ROOT / "measurements"
README = ROOT / "README.md"

RAW_KEYS = ["flash_text", "flash_data", "static_bss", "heap_used", "stack_log", "stack_service"]

# Derived, marketing-facing columns from the raw self-measured keys.
#   Flash      = read-only image (.text + .rodata) + .data init image
#   Static RAM = .data (copied to RAM) + .bss
DERIVED = [
    ("Flash", lambda d: d["flash_text"] + d["flash_data"]),
    ("Static RAM", lambda d: d["flash_data"] + d["static_bss"]),
    ("Heap", lambda d: d["heap_used"]),
    ("Log stack", lambda d: d["stack_log"]),
    ("Service stack", lambda d: d["stack_service"]),
]


def load_csv(state):
    values = {}
    for line in (MEAS / f"{state}.csv").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition(",")
        if key in RAW_KEYS:
            values[key] = int(value)
    missing = [k for k in RAW_KEYS if k not in values]
    if missing:
        raise SystemExit(f"{state}.csv missing keys: {missing}")
    return values


def load_states():
    rows = []
    for line in (MEAS / "tags.tsv").read_text(encoding="utf-8").splitlines():
        line = line.rstrip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 2:
            raise SystemExit(f"tags.tsv row must be state<TAB>what-it-adds: {line!r}")
        rows.append(parts)
    return rows


def main():
    states = load_states()
    base_state = states[0][0]
    base = {name: fn(load_csv(base_state)) for name, fn in DERIVED}

    header = ["State", "What it adds"] + [name for name, _ in DERIVED]
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join(["---"] * len(header)) + "|"]

    for state, what in states:
        cur = load_csv(state)
        cells = [state, what]
        if state == base_state:
            cells += ["baseline" for _ in DERIVED]
        else:
            cells += [f"{fn(cur) - base[name]:+,}" for name, fn in DERIVED]
        lines.append("| " + " | ".join(cells) + " |")

    table = "\n".join(lines)
    base_note = "*Baseline: " + ", ".join(f"{name} {base[name]:,} B" for name, _ in DERIVED) + ".*"

    block = (
        "<!-- COST-TABLE:START (generated by scripts/gen-cost-table.py — do not edit by hand) -->\n\n"
        f"{table}\n\n{base_note}\n\n"
        "<!-- COST-TABLE:END -->"
    )

    text = README.read_text(encoding="utf-8")
    new_text, n = re.subn(r"<!-- COST-TABLE:START.*?COST-TABLE:END -->", block, text, count=1, flags=re.S)
    if n != 1:
        raise SystemExit("COST-TABLE markers not found in README.md")
    README.write_text(new_text, encoding="utf-8", newline="\n")
    print(f"updated README cost table ({len(states)} state(s))")


if __name__ == "__main__":
    main()
